### ISSUE TITLE
Runtime Error: forward() got an unexpected keyword argument 'cache_position'

### ISSUE THREAD

**Issue by Meng-Fanshu** [FreedomIntelligence/HuatuoGPT-Vision#2]
code:
query = 'What does the picture show?'
image_paths = ['/home/downloads/test.jpg']

huatuogpt_vision_model_path = "/home/llm_models/HuatuoGPT-Vision-7B"

from cli import HuatuoChatbot
bot = HuatuoChatbot(huatuogpt_vision_model_path)
output = bot.inference(query, image_paths)
print(output) # Prints the output of the model

Error Info:
/home/mengfanshu/workplace/HuatuoGPT-Vision
loading from /home/llm_models/HuatuoGPT-Vision-7B
loading from CLIP first. This should only be used at inference!!!
loading vision model from openai/clip-vit-large-patch14-336
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00,  4.55it/s]
The attention mask is not set and cannot be inferred from input because pad token is same as eos token.As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Traceback (most recent call last):
  File "/home/mengfanshu/workplace/HuatuoGPT-Vision/quickStart.py", line 8, in <module>
    output = bot.inference(query, image_paths)
  File "/home/mengfanshu/workplace/HuatuoGPT-Vision/cli.py", line 276, in inference
    output_ids = self.model.generate(
  File "/home/mengfanshu/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/mengfanshu/workplace/HuatuoGPT-Vision/llava/model/language_model/llava_qwen2.py", line 150, in generate
    return super().generate(
  File "/home/mengfanshu/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/mengfanshu/miniconda3/envs/pytorch/lib/python3.9/site-packages/transformers/generation/utils.py", line 1989, in generate
    result = self._sample(
  File "/home/mengfanshu/miniconda3/envs/pytorch/lib/python3.9/site-packages/transformers/generation/utils.py", line 2932, in _sample
    outputs = self(**model_inputs, return_dict=True)
  File "/home/mengfanshu/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mengfanshu/miniconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: forward() got an unexpected keyword argument 'cache_position'

**Comment by HuichiZhou** [comment]
Hello, you should `pip install transformer==4.37.2`

**Comment by SiddhantOjha17** [comment]
how did you download the model ?

**Comment by mrjzz** [comment]
> how did you download the model ?

Is the way of model-downloading relevant with this error?

**Comment by mrjzz** [comment]
> Hello, you should `pip install transformer==4.37.2`
Thx, it works.

**Comment by Teddy-SC** [comment]
> Hello, you should `pip install transformer==4.37.2`

what version of python are you using? I want to install transformer but it keeps saying conflict.

**Comment by Teddy-SC** [comment]
transformers==4.37.2 always has conflict，transformers==4.37 still work.

**Comment by GeoJX** [comment]
I can't download the model even with transformers==4.37.2 , and the error as fellow:Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
tokenizer_config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.30k/1.30k [00:00<00:00, 3.89MB/s]
vocab.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.78M/2.78M [00:00<00:00, 3.54MB/s]
merges.txt: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.67M/1.67M [00:00<00:00, 37.5MB/s]
tokenizer.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7.03M/7.03M [00:00<00:00, 22.7MB/s]
added_tokens.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 80.0/80.0 [00:00<00:00, 310kB/s]
special_tokens_map.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 256/256 [00:00<00:00, 1.01MB/s]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.07k/1.07k [00:00<00:00, 3.73MB/s]
Traceback (most recent call last):
  File "/root/miniconda3/envs/deepseek/lib/python3.12/site-packages/transformers/models/auto/configuration_auto.py", line 1117, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
                   ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/deepseek/lib/python3.12/site-packages/transformers/models/auto/configuration_auto.py", line 813, in __getitem__
    raise KeyError(key)
KeyError: 'llava_qwen2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/geo/D241411/Med_Work/model_download.py", line 13, in <module>
    model = AutoModel.from_pretrained(model_name, cache_dir=save_path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/deepseek/lib/python3.12/site-packages/transformers/models/auto/auto_factory.py", line 526, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/deepseek/lib/python3.12/site-packages/transformers/models/auto/configuration_auto.py", line 1119, in from_pretrained
    raise ValueError(
ValueError: The checkpoint you are trying to load has model type `llava_qwen2` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.
(deepseek) (base) root@s246:/home/geo/D241411#

**Comment by GeoJX** [comment]
I can't download the model even with transformers==4.37.2 , and the error as fellow:Downloads always resume when possible. If you want to force a new download, use force_download=True.
warnings.warn(
tokenizer_config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.30k/1.30k [00:00<00:00, 3.89MB/s]
vocab.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.78M/2.78M [00:00<00:00, 3.54MB/s]
merges.txt: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.67M/1.67M [00:00<00:00, 37.5MB/s]
tokenizer.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7.03M/7.03M [00:00<00:00, 22.7MB/s]
added_tokens.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 80.0/80.0 [00:00<00:00, 310kB/s]
special_tokens_map.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 256/256 [00:00<00:00, 1.01MB/s]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.07k/1.07k [00:00<00:00, 3.73MB/s]
Traceback (most recent call last):
File "/root/miniconda3/envs/deepseek/lib/python3.12/site-packages/transformers/models/auto/configuration_auto.py", line 1117, in from_pretrained
config_class = CONFIG_MAPPING[config_dict["model_type"]]
~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/root/miniconda3/envs/deepseek/lib/python3.12/site-packages/transformers/models/auto/configuration_auto.py", line 813, in getitem
raise KeyError(key)
KeyError: 'llava_qwen2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "//model_download.py", line 13, in
model = AutoModel.from_pretrained(model_name, cache_dir=save_path)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/root/miniconda3/envs/deepseek/lib/python3.12/site-packages/transformers/models/auto/auto_factory.py", line 526, in from_pretrained
config, kwargs = AutoConfig.from_pretrained(
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/root/miniconda3/envs/deepseek/lib/python3.12/site-packages/transformers/models/auto/configuration_auto.py", line 1119, in from_pretrained
raise ValueError(
ValueError: The checkpoint you are trying to load has model type llava_qwen2 but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.
